name: "Pre-Release"
on:
    push:
        tags-ignore:
            - "v*"
    pull_request:
        tags-ignore:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'

            -   name: Get POM Version
                uses: entimaniac/read-pom-version-action@1.0.0
                id: getVersion

            -   name: Build with Maven
                run: mvn clean package

            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: ProxyChat-${{ steps.getVersion.outputs.version }}
                    path: ./target/ProxyChat.jar